### ISSUE TITLE
Reconsider icon assignment for json

### ISSUE THREAD

**Issue by AndydeCleyre** [Electrux/ls_extended#35]
What's the idea behind assigning `.json` files `ﬥ U+FB25 HEBREW LETTER WIDE LAMED`?

FWIW the `lsd` project uses ` U+E60B`.

EDIT: I see at the [Nerd Fonts site](https://www.nerdfonts.com/cheat-sheet) that they indeed use `fb25` as `nf-mdi-json` as well as `e60b` as `nf-seti-json`. I have a preference for the latter as it's in the private use area, while the former is part of an alphabet.

But I understand most users will have nerd-patched fonts, and get it if this is rejected if `fb25` is generally preferred.

**Comment by Chirag-Khandelwal** [comment]
Hey!
Thanks a lot for the suggestion, really appreciate it 😄.
However, apologies, but I won't be able to apply it since, as you say, `fb25` is generally preferred.
On a more positive note, you can easily fork/clone the repository and modify to your liking [here](https://github.com/Electrux/ls_extended/blob/1707381df19b09317b5ce5512ca0eea9126a2e45/src/icons.c#L96) (which you probably already know haha 😉).
